name: PHPStan

on:
  push:
    branches: [master, main, '*.x']
  pull_request:

jobs:
  phpstan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, intl, imagick
          coverage: none
          tools: composer:v2

      - name: Install dependencies
        run: composer update --no-interaction --prefer-dist

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse --memory-limit=1G --no-progress
